const express=require('express');
const bodyparser=require('body-parser');
const exphbs=require('express-handlebars');
const type=require('./routes/Typefunctions');
const location=require('./routes/Locationfunctions');
const project=require('./routes/Projectfunctions');
const routes=require('./routes/index');
const path=require('path');
const app=express();
const PORT=process.env.PORT||8080;
app.engine('handlebars',exphbs({defaultLayout:'main'}));
app.use(express.static(path.join(__dirname,'public')));
app.set('view engine','handlebars');
app.use(bodyparser.urlencoded({extended:true}));
app.use(bodyparser.json());
app.use('/type',type);
app.use('/location',location);
app.use('/project',project);
app.use('/',routes);
app.listen(PORT,()=>{
    console.log('server started on '+PORT);
});